name: breeze
description: "Minimalistic and modern tasks app"
publish_to: "none"
version: 1.2.6

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  supabase: ^2.6.3
  supabase_flutter: ^2.8.4
  flutter_svg: ^2.0.17
  toastification: ^3.0.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  desktop_window: ^0.4.2
  msix: ^3.16.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/

msix_config:
  display_name: Breeze
  publisher_display_name: AS
  identity_name: com.as.project-breeze
  msix_version: 1.2.6.0
  logo_path: windows/runner/resources/app_icon.ico
